### ISSUE TITLE
Deezer support

### ISSUE THREAD

**Issue by NAUSHNIK52** [cgravolet/scroblr#115]
Please add support for French music streaming service Deezer.com

**Comment by NAUSHNIK52** [comment]
Thanks you! @cgravolet, can you push it to Chrome Web Store please? Or at least explain me why building fails for me? Running Linux Mint 18, followed guide from wiki.
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle scroblr@2.2.4~prebuild: scroblr@2.2.4
6 silly lifecycle scroblr@2.2.4~prebuild: no script for prebuild, continuing
7 info lifecycle scroblr@2.2.4~build: scroblr@2.2.4
8 verbose lifecycle scroblr@2.2.4~build: unsafe-perm in lifecycle true
9 verbose lifecycle scroblr@2.2.4~build: PATH: /usr/share/npm/bin/node-gyp-bin:/home/artem/scroblr/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle scroblr@2.2.4~build: CWD: /home/artem/scroblr
11 silly lifecycle scroblr@2.2.4~build: Args: [ '-c', 'grunt' ]
12 info lifecycle scroblr@2.2.4~build: Failed to exec build script
13 verbose stack Error: scroblr@2.2.4 build: `grunt`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid scroblr@2.2.4
15 verbose cwd /home/artem/scroblr
16 error Linux 4.4.0-31-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error scroblr@2.2.4 build: `grunt`
24 error spawn ENOENT
25 error Failed at the scroblr@2.2.4 build script 'grunt'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the scroblr package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     grunt
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs scroblr
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls scroblr
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]`
